# Generated by Django 3.0.8 on 2020-07-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200727_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followee',
            new_name='target_user',
        ),
    ]
